apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-storage
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-storage
  template:
    metadata:
      labels:
        app: file-storage
    spec:
      containers:
      - name: file-storage
        image: hushhrf/file-storage:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: app-config
        env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DB_PASSWORD
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://eureka-server:8761/eureka"
        - name: SPRING_APPLICATION_JSON
          value: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://eureka-server:8761/eureka"}}}}'
        - name: SPRING_APPLICATION_NAME
          value: "file-storage"
        - name: JAVA_TOOL_OPTIONS
          value: "-Xms64m -Xmx192m"
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 5
        resources:
          requests:
            memory: "96Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"

      initContainers:
      - name: wait-for-config-server
        image: busybox:1.35
        command: ['sh', '-c', 'until nc -z config-server 8888; do echo waiting for config-server; sleep 2; done;']
      - name: wait-for-eureka
        image: busybox:1.35
        command: ['sh', '-c', 'until nc -z eureka-server 8761; do echo waiting for eureka-server; sleep 2; done;']
